######################################################################
# Automatically generated by qmake (2.01a) Mon Oct 24 02:42:59 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QMAKE_CXXFLAGS += -std=c++11

# Input
HEADERS += Bag.h \
           Board.h \
           Dictionary.h \
           main_window.h \
           mainNext_window.h \
           naming_window.h \
           player.h \
           Square.h \
           starting_window.h \
           Tile.h
SOURCES += Bag.cpp \
           Board.cpp \
           Dictionary.cpp \
           main_window.cpp \
           mainNext_window.cpp \
           naming_window.cpp \
           player.cpp \
           Square.cpp \
           starting_window.cpp \
           testmain.cpp
